// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bwlvvittoqtjzqahrtvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ3bHZ2aXR0b3F0anpxYWhydHZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1MDMwMTYsImV4cCI6MjA2ODA3OTAxNn0.sUreb7KweW0uBf-5yDD0_y_MoFW29qoWjOl-4gn9WYQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});